# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](https://github.com/himike1973/6m-data-1.6-intro-numpy/blob/main/assets/numpy_vs_python_list.png?raw=1)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [ ]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](https://github.com/himike1973/6m-data-1.6-intro-numpy/blob/main/assets/numpy_ndarray.png?raw=1)

In [ ]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [ ]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
print("Casted to int32:", arr.astype(np.int32))

### 🛠️ Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [ ]:
# Your code here


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](https://github.com/himike1973/6m-data-1.6-intro-numpy/blob/main/assets/vectorization.png?raw=1)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [ ]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax.

### 2D Array Indexing Syntax
![2d_array_indexing](https://github.com/himike1973/6m-data-1.6-intro-numpy/blob/main/assets/ndarray_axis_index.png?raw=1)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [ ]:
# [DEMO] Slicing views
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 12345
print("Original array modified via slice:", arr)

# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])

### 🛠️ Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [ ]:
# Your code here


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [ ]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

### 🛠️ Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [ ]:
# Your code here


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays.

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [ ]:
# [DEMO] Statistical Methods
arr = np.random.randn(3, 4)
print("Random Array:\n", arr)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](https://github.com/himike1973/6m-data-1.6-intro-numpy/blob/main/assets/matrix_multiplication.png?raw=1)

In [ ]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

### 🛠️ Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [ ]:
# Your code here
testing updates

**Warm-up: Rebuild the basics**

Goal: Make array creation and inspection feel automatic.

Create each of the following arrays and print its shape, ndim, and dtype:

1.   1D array of integers from 10 to 19
2.   2D array of shape (4, 3) filled with 1.5
3.   3D array of zeros with shape (2, 2, 3)

Convert the (4, 3) float array to integers using .astype(int).

Write down (in a markdown cell) when you would prefer float vs int in real analyst work (e.g., prices vs counts).

In [ ]:
import numpy as np
x = np.array([10,11,12,13,14,15,16,17,18,19])
print ("1D Array", x)
print(f"Shape: {x.shape}, Dimensions: {x.ndim}, Dtype: {x.dtype}")

array_2d = np.full((4,3), 1.5)
print ("2D Array", array_2d)
print (f"Shape: {array_2d.shape}, Dimensions: {array_2d.ndim}, Dtype: {array_2d.dtype}")

array_3d = np.zeros((2,2,3))
print ("3D Array", array_3d)
print (f"Shape: {array_3d.shape}, Dimensions: {array_3d.ndim}, Dtype: {array_3d.dtype}")

array_2dint = array_2d.astype(int)
print ("2D Array Int", array_2dint)

1D Array [10 11 12 13 14 15 16 17 18 19]
Shape: (10,), Dimensions: 1, Dtype: int64
2D Array [[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Shape: (4, 3), Dimensions: 2, Dtype: float64
3D Array [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
Shape: (2, 2, 3), Dimensions: 3, Dtype: float64
2D Array Int [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


### Float vs. Int in Analyst Work

**Integers (`int`)** are best suited for:
*   **Counts**: When representing discrete whole numbers, such as the number of items sold, unique visitors, or occurrences of an event. For example, `number_of_transactions = 150`.
*   **Identifiers**: IDs for customers, products, or transactions.
*   **Quantities that cannot be fractional**: Like the number of employees or people.

**Floating-point numbers (`float`)** are best suited for:
*   **Prices and Monetary Values**: Where values can have decimal components, such as `$19.99` or a discount of `5.5%`.
*   **Measurements**: Any physical measurement that can be fractional, like weight, height, temperature, or duration.
*   **Percentages and Ratios**: When dealing with values that represent parts of a whole.
*   **Averages and Calculated Metrics**: Often, an average or a derived metric will result in a non-integer value, even if the underlying data was integer-based.

**2. Sales table drill: Indexing and slicing**

Scenario: You have quarterly sales numbers for 4 regions (rows) over 5 quarters (columns).

```
# import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])
```

Do the following:

Select all quarters for Region B as a 1D array.

Select Q2 to Q4 (inclusive) for all regions as a 2D subarray.

Select Q5 sales for Regions A and D only (use slicing or fancy indexing).

Compute the shape of each result and add a brief comment: “Is this 1D or 2D, and why?”

In [ ]:
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])
print (sales.shape)
print (regions.shape)
print (quarters.shape)

print (sales[1]) # Region B as 1D Array
print("\n" + "-"*50 + "\n")
print ("All Region", quarters[1:4], "\n", sales[:,1:4] ) #All Region Q2 to Q4
print("\n" + "-"*50 + "\n")
print (quarters[4], regions[1], sales[0,4], regions[3], sales[3,4]) #

(4, 5)
(4,)
(5,)
[ 90  85  95 100 110]

--------------------------------------------------

All Region ['Q2' 'Q3' 'Q4'] 
 [[135 110 145]
 [ 85  95 100]
 [215 190 225]
 [140 135 160]]

--------------------------------------------------

Q5 B 130 D 170


In [ ]:
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])

# 1. Select all quarters for Region B as a 1D array.
region_b_sales = sales[1]
print("1. Sales for Region B:", region_b_sales)
print("   Shape:", region_b_sales.shape, ", Is this 1D or 2D, and why? This is 1D because we selected a single row (Region B), which collapses to a 1D array of sales values.")

print("\n" + "-"*50 + "\n")

# 2. Select Q2 to Q4 (inclusive) for all regions as a 2D subarray.
q2_to_q4_all_regions = sales[:, 1:4]
print("2. Sales for Q2 to Q4 for all regions:\n", q2_to_q4_all_regions)
print("   Shape:", q2_to_q4_all_regions.shape, ", Is this 1D or 2D, and why? This is 2D because we selected multiple rows (all regions) and multiple columns (Q2-Q4), preserving the 2D structure.")

print("\n" + "-"*50 + "\n")

# 3. Select Q5 sales for Regions A and D only (use slicing or fancy indexing).
q5_region_ad_sales = sales[[0, 3], 4]
print("3. Q5 sales for Regions A and D:", q5_region_ad_sales)
print("   Shape:", q5_region_ad_sales.shape, ", Is this 1D or 2D, and why? This is 1D because we selected specific rows (A and D) and a single column (Q5), which results in a 1D array of sales values.")


1. Sales for Region B: [ 90  85  95 100 110]
   Shape: (5,) , Is this 1D or 2D, and why? This is 1D because we selected a single row (Region B), which collapses to a 1D array of sales values.

--------------------------------------------------

2. Sales for Q2 to Q4 for all regions:
 [[135 110 145]
 [ 85  95 100]
 [215 190 225]
 [140 135 160]]
   Shape: (4, 3) , Is this 1D or 2D, and why? This is 2D because we selected multiple rows (all regions) and multiple columns (Q2-Q4), preserving the 2D structure.

--------------------------------------------------

3. Q5 sales for Regions A and D: [130 170]
   Shape: (2,) , Is this 1D or 2D, and why? This is 1D because we selected specific rows (A and D) and a single column (Q5), which results in a 1D array of sales values.


# 3. Boolean masks: Work with targets
Scenario: You have campaign response data.


```
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue
```
1.   Compute the ROI for each person: roi = revenue / spend.
2.   Create a boolean mask for customers with roi >= 2.0.
3. Use the mask to:
  *   List their names
  *   List their spend and revenue
4. Create a second mask for customers with spend >= 200.
5. Combine the two masks to find customers who have roi >= 2.0 AND spend >= 200.
6. In a markdown cell, answer: “What business insight do you get from this filtered group?”

In [ ]:
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue

#1 ROI for Each Person
ROI = revenue /spend
print ("#1 ROI for each",np.round(ROI, 2))
print("\n" + "-"*50 + "\n")
#2 Boolean mask
roi_mask = (ROI >= 2.0)
print("#2 ROI >= 2.0:", roi_mask)
print("\n" + "-"*50 + "\n")
#3 Use Mask to list
print("#3a Names ROI >=2.0", names[roi_mask])
print("#3b Spend/Revenue:", spend[roi_mask], revenue[roi_mask])
print("\n" + "-"*50 + "\n")
#4 Mask for customer spend >200
spend_mask = (spend >= 200)
print("#4 Spend >= 200:", names[spend_mask])
print("\n" + "-"*50 + "\n")
#5 Combine the two masks to find customers who have roi >= 2. and spend  >200
combined_mask = (roi_mask & spend_mask)
print("#5 Combined Mask:", names[combined_mask])
#

#1 ROI for each [2.   1.2  1.67 0.83 1.22 1.18 0.94 1.94]

--------------------------------------------------

#2 ROI >= 2.0: [ True False False False False False False False]

--------------------------------------------------

#3a Names ROI >=2.0 ['Ana']
#3b Spend/Revenue: [200] [400]

--------------------------------------------------

#4 Spend >= 200: ['Ana' 'Chen' 'Fatima' 'Hui']

--------------------------------------------------

#5 Combined Mask: ['Ana']


### Business Insight from Filtered Group

From the combined filter (ROI >= 2.0 AND Spend >= 200), we observe that **only 'Ana' meets both criteria**. This indicates that 'Ana' is a highly valuable customer, demonstrating both high engagement (ROI) and significant investment (Spend).

This group represents our most efficient and impactful marketing efforts. Further investigation into 'Ana's' customer journey and characteristics could provide valuable insights for targeting similar high-potential customers and optimizing future campaigns.

# 4. Gradebook: Aggregations and broadcasting
Reuse the “Gradebook” idea from class and extend it.


```
# students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])
```
1. Compute each student’s average score (per row).
2. Compute each subject’s average score (per column).
3. Create scores_centered by subtracting the subject mean from each column (broadcasting).
4. For scores_centered, compute per-student averages again.
5. Compare which student looks best by raw average vs centered average.
5. In a markdown cell, explain briefly why centered scores might give a fairer comparison.

In [ ]:
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])

# 1. Compute each student’s average score (per row).
student_avg_scores = np.mean(scores, axis=1)

print("1. Student Average Scores:", student_avg_scores)
print("-"*50)
# 2. Compute each subject’s average score (per column).
subject_avg_scores = np.mean(scores, axis=0)
print("2. Subject Average Scores:", subject_avg_scores)

1. Student Average Scores: [80.         65.         90.         81.66666667 73.33333333]
--------------------------------------------------
2. Subject Average Scores: [75.4 76.8 81.8]
